package kr.co.polycube.backendtest.domain.lotto;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@Entity
@Table(name = "tbl_winner")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WinnerEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(unique = true, nullable = false)
    private Long id;

    @Column(nullable = false)
    private Long lotto_id;

    @Column
    private int rank;

    /*
    drop table tbl_winner;
    CREATE TABLE tbl_winner (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            lotto_id INT,
            rank INT,
            PRIMARY KEY (id)
    );


select * from tbl_lotto;
select * from tbl_winner;
 */

}
